/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'
import { Route as KnowledgeServicesRouteImport } from './routes/knowledge.services'
import { Route as KnowledgeLocationsRouteImport } from './routes/knowledge.locations'
import { Route as KnowledgeFaqRouteImport } from './routes/knowledge.faq'
import { Route as KnowledgeDocumentsRouteImport } from './routes/knowledge.documents'
import { Route as KnowledgeContactRouteImport } from './routes/knowledge.contact'
import { Route as KnowledgeBusinessHoursRouteImport } from './routes/knowledge.business-hours'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProspectsRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspectsRoute,
} as any)
const KnowledgeServicesRoute = KnowledgeServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeLocationsRoute = KnowledgeLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeFaqRoute = KnowledgeFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeDocumentsRoute = KnowledgeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeContactRoute = KnowledgeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeBusinessHoursRoute = KnowledgeBusinessHoursRouteImport.update({
  id: '/business-hours',
  path: '/business-hours',
  getParentRoute: () => KnowledgeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/users': typeof UsersRoute
  '/knowledge/business-hours': typeof KnowledgeBusinessHoursRoute
  '/knowledge/contact': typeof KnowledgeContactRoute
  '/knowledge/documents': typeof KnowledgeDocumentsRoute
  '/knowledge/faq': typeof KnowledgeFaqRoute
  '/knowledge/locations': typeof KnowledgeLocationsRoute
  '/knowledge/services': typeof KnowledgeServicesRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/knowledge/business-hours': typeof KnowledgeBusinessHoursRoute
  '/knowledge/contact': typeof KnowledgeContactRoute
  '/knowledge/documents': typeof KnowledgeDocumentsRoute
  '/knowledge/faq': typeof KnowledgeFaqRoute
  '/knowledge/locations': typeof KnowledgeLocationsRoute
  '/knowledge/services': typeof KnowledgeServicesRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/prospects': typeof ProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/users': typeof UsersRoute
  '/knowledge/business-hours': typeof KnowledgeBusinessHoursRoute
  '/knowledge/contact': typeof KnowledgeContactRoute
  '/knowledge/documents': typeof KnowledgeDocumentsRoute
  '/knowledge/faq': typeof KnowledgeFaqRoute
  '/knowledge/locations': typeof KnowledgeLocationsRoute
  '/knowledge/services': typeof KnowledgeServicesRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/prospects'
    | '/users'
    | '/knowledge/business-hours'
    | '/knowledge/contact'
    | '/knowledge/documents'
    | '/knowledge/faq'
    | '/knowledge/locations'
    | '/knowledge/services'
    | '/prospects/$id'
    | '/knowledge/'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/integrations'
    | '/login'
    | '/users'
    | '/knowledge/business-hours'
    | '/knowledge/contact'
    | '/knowledge/documents'
    | '/knowledge/faq'
    | '/knowledge/locations'
    | '/knowledge/services'
    | '/prospects/$id'
    | '/knowledge'
    | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/prospects'
    | '/users'
    | '/knowledge/business-hours'
    | '/knowledge/contact'
    | '/knowledge/documents'
    | '/knowledge/faq'
    | '/knowledge/locations'
    | '/knowledge/services'
    | '/prospects/$id'
    | '/knowledge/'
    | '/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProspectsRoute: typeof ProspectsRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof ProspectsRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof ProspectsRoute
    }
    '/knowledge/services': {
      id: '/knowledge/services'
      path: '/services'
      fullPath: '/knowledge/services'
      preLoaderRoute: typeof KnowledgeServicesRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/locations': {
      id: '/knowledge/locations'
      path: '/locations'
      fullPath: '/knowledge/locations'
      preLoaderRoute: typeof KnowledgeLocationsRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/faq': {
      id: '/knowledge/faq'
      path: '/faq'
      fullPath: '/knowledge/faq'
      preLoaderRoute: typeof KnowledgeFaqRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/documents': {
      id: '/knowledge/documents'
      path: '/documents'
      fullPath: '/knowledge/documents'
      preLoaderRoute: typeof KnowledgeDocumentsRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/contact': {
      id: '/knowledge/contact'
      path: '/contact'
      fullPath: '/knowledge/contact'
      preLoaderRoute: typeof KnowledgeContactRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/business-hours': {
      id: '/knowledge/business-hours'
      path: '/business-hours'
      fullPath: '/knowledge/business-hours'
      preLoaderRoute: typeof KnowledgeBusinessHoursRouteImport
      parentRoute: typeof KnowledgeRoute
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeBusinessHoursRoute: typeof KnowledgeBusinessHoursRoute
  KnowledgeContactRoute: typeof KnowledgeContactRoute
  KnowledgeDocumentsRoute: typeof KnowledgeDocumentsRoute
  KnowledgeFaqRoute: typeof KnowledgeFaqRoute
  KnowledgeLocationsRoute: typeof KnowledgeLocationsRoute
  KnowledgeServicesRoute: typeof KnowledgeServicesRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeBusinessHoursRoute: KnowledgeBusinessHoursRoute,
  KnowledgeContactRoute: KnowledgeContactRoute,
  KnowledgeDocumentsRoute: KnowledgeDocumentsRoute,
  KnowledgeFaqRoute: KnowledgeFaqRoute,
  KnowledgeLocationsRoute: KnowledgeLocationsRoute,
  KnowledgeServicesRoute: KnowledgeServicesRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ProspectsRouteChildren {
  ProspectsIdRoute: typeof ProspectsIdRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
}

const ProspectsRouteChildren: ProspectsRouteChildren = {
  ProspectsIdRoute: ProspectsIdRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
}

const ProspectsRouteWithChildren = ProspectsRoute._addFileChildren(
  ProspectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LoginRoute: LoginRoute,
  ProspectsRoute: ProspectsRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
